/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "motd.h"
#include <stdio.h>
#include <stdlib.h>

void motd_prog_1(char *host, char *message)
{
    CLIENT *clnt;
    int *result_1;
    char *count_1_arg;
    char **result_2;
    int get_1_arg;
    void *result_3;
    char *add_1_arg;

#ifndef DEBUG
    clnt = clnt_create(host, MOTD_PROG, MOTD_VERS, "udp");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif /* DEBUG */

    if (message != NULL)
    {
        // Add message
        char *add_1_arg = message;
        void *result = add_1(&add_1_arg, clnt);
        if (result == (void *)NULL)
        {
            clnt_perror(clnt, "add_1 call failed");
            exit(EXIT_FAILURE);
        }
    }
    else
    {
        // Print history
        char *count_1_arg;
        int *np = count_1((void *)&count_1_arg, clnt);
        if (np == (int *)NULL)
        {
            clnt_perror(clnt, "count_1 call failed");
            exit(EXIT_FAILURE);
        }

        for (int i = 0; i < *np; i++)
        {
            char **spp = get_1(&i, clnt);
            if (spp == (char **)NULL)
            {
                clnt_perror(clnt, "get_1 call failed");
                exit(EXIT_FAILURE);
            }
            printf("%s\n", *spp);
        }
    }
#ifndef DEBUG
    clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
    if (argc < 2 || argc > 3)
    {
        printf("usage: %s server_host [message]\n", argv[0]);
        exit(1);
    }
    if (argc == 3)
        motd_prog_1(argv[1], argv[2]);
    else
        motd_prog_1(argv[1], NULL);
    exit(EXIT_SUCCESS);
}
